### ISSUE TITLE
Image Stack failes to open with Segmentation Fault

### ISSUE THREAD

**Issue by dEvasEnApati** [janelia-flyem/NeuTu#10]
Dear Neutu developers

Thank you very much for developing this very nice piece of software. It's  a very useful when comparing a reconstruction and it's corresponding image stack.

When I try to import some of my image stacks, Neutu crashes with a segmentation fault. I am using an installation which I got by compiling the source on my Ubuntu 14.04 machine.

Here is a test file: https://copy.com/gDqPfJr36GYxiSoa

Could you please have a look.

Thanks
Ajay

**Comment by tingzhao** [comment]
There seems some inconsistency in the metadata of the image file. We'll fix the problem. BTW, which branch are you using?

**Comment by dEvasEnApati** [comment]
Thanks. I am using the branch 'public'.

**Comment by tingzhao** [comment]
The fix has been pushed into the public branch. The data should be loaded normally now.

**Comment by tingzhao** [comment]
I assume the issue has been fixed. Ajay, please open a new issue if there are any problems.
