### ISSUE TITLE
Isometric projection for 3d view

### ISSUE THREAD

**Issue by AndrewMicallef** [janelia-flyem/NeuTu#11]
Is it possible to alter the 3d camera to remove the default perspective projection?

It is really nice to look at, but I find the 3d view almost useless because the perspective projection makes orientation confusing.

Also it would be really nice to have hotkeys for orthogonal views. 
You already use the number pad for rotating the camera, so it might be nice to steal the blender hotkeys in this instance. (numpad 1 for front [z-x projection], numpad 3 for left [z-y projection], numpad 7 for top [x-y])

**Comment by tingzhao** [comment]
Maybe the 'Orthographic' option in the Projection Type of the General tab in Control and Settings is something you're looking for?
The hotkeys sound reasonable and we'll consider to add them.

**Comment by AndrewMicallef** [comment]
Ahh, I don't seem to have that option in the General tab.

I'm using the Windows General Edition (1.0z.2016) available from http://www.neutracing.com/download/

![general settings](https://cloud.githubusercontent.com/assets/7134339/21122411/0d8b2d92-c126-11e6-833e-02c1ff29d49d.png)

**Comment by tingzhao** [comment]
I see. We removed the option from the release version because no one seemed using it. We'll add it back.

**Comment by tingzhao** [comment]
We have added it back in the latest version (patched 2017.1.09)
