### ISSUE TITLE
saving preferences

### ISSUE THREAD

**Issue by AndrewMicallef** [janelia-flyem/NeuTu#12]
Is it possible to save the default trace settings? At the moment each time I start up neuTube I set all the configs to minimize the amount of auto tracing that the program does (my images are too noisy for auto tracing to be reliable)

Also, a nice addition would be a completely manual tracing mode. Keeping the same work flow, except extending nodes does a simple linear interpolation without adding additional nodes in between.

**Comment by tingzhao** [comment]
For the completely manual tracing, it is 'Ctrl/Cmd + mouse click'.

You can edit the json file (json/trace_config.json) under the program directory. To save tracing time and reduce branches, you increase "minimalScoreAuto", set "recover" to 0 and "truneEnd" to false.
Here is the description of the default fields for more details:
"default": {
      "description": "Default parameter values",
      "type": "object":,
      "properties": {
        "minimalScoreAuto": {
          "description": "Minimal auto tracing score",
          "type": "number",
          "minimum": 0,
          "maximum": 1
        },
        "minimalScoreSeed": {
          "description": "Minimal score screening score",
          "type": "number",
          "minimum": 0,
          "maximum": 1
        },
        "refit": {
          "description": "Aggressive parameter searching while the fitting score is too low after initial fitting",
          "type": "boolean"
        },
        "spTest": {
          "description": "Use signal path to evaluate the connection strength between two branches",
          "type": "boolean"
        },
        "crossoverTest": {
          "description": "Detect crossover patterns",
          "type": "boolean"
        },
        "tuneEnd": {
          "description": "Fine tuning of the terminal of a traced branch",
          "type": "boolean"
        },
        "edgePath": {
          "description": "Run signal path test on edge detection",
          "type": "boolean"
        },
        "enhanceMask": {
          "description": "More aggressive seed detection",
          "type": "boolean"
        },
        "seedMethod": {
          "description": "Seeding method",
          "type": "integer"
        }
      }
    }
