### ISSUE TITLE
Todos persist if they are highlighted.

### ISSUE THREAD

**Issue by knechtc** [janelia-flyem/NeuTu#126]
In Neu3,  Todo's placed on a body will persist through an assignment if the todo is selected/highlighted when the user activates the 'next' button to navigate between bodies.

**Comment by tingzhao** [comment]
Is it easy to reproduce the problem? I couldn't reproduce it.

**Comment by tingzhao** [comment]
There is indeed a bug that can cause persisting todos, no matter whether a todo is selected or not. It might be related to the issue #146

**Comment by knechtc** [comment]
At the original time of posting you could reproduce the issue consistently. Presently we were unable to reproduce the issue at all.
