### ISSUE TITLE
Cannot install NeuTu via conda

### ISSUE THREAD

**Issue by constantinpape** [janelia-flyem/NeuTu#14]
I have tried to install NeuTu via conda:

$ conda create -n neutu -c flyem neutu

However, this fails with an error message, telling me that conda can't find the package:

```
Fetching package metadata: ......
Solving package specifications: .
Error:  Package missing in current linux-64 channels: 
  - neutu
```

I have tried this on two different machines, both running Ubuntu 14.04 with the latest Miniconda2 version.

**Comment by tingzhao** [comment]
Currently the conda install only supports Mac. While we're working on a conda package for linux, you can also build NeuTu on linux by downloading the code and running the building script. You can find the instructions in the 'Build' section on this page:
https://github.com/janelia-flyem/NeuTu/tree/flyem_release

**Comment by constantinpape** [comment]
Ok, thanks.
Building from source worked.
