### ISSUE TITLE
Save final cleave response to dvid, verbatim

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/NeuTu#141]
The cleave-server response includes not only assignments, but also other useful information, such as the user, timestamp, cleave seeds, uuid, and warnings.  Instead of saving only the assignments to DVID, it would be convenient for downstream analysis and debugging if neu3 would store the entire JSON response from the cleave server.

**Comment by stuarteberg** [comment]
I'd like to bump the priority of this, please, even if you have to save it in a separate key-value instance.

(I'm on another debugging expedition today, and having the complete cleave-response would help me figure out what's going on.)

**Comment by hubbardp** [comment]
Now in the "neu3-body-cleave-save-server-reply" branch:
https://github.com/janelia-flyem/NeuTu/commit/db17fd40d56fa761c32ec094a62ab8ad96fca1c8

**Comment by stuarteberg** [comment]
thanks!

**Comment by hubbardp** [comment]
Now released for testing in /groups/flyem/data/shared/test/testCleaving/bin/neu3.

**Comment by hubbardp** [comment]
The merge into the "develop" branch is pending:
https://github.com/janelia-flyem/NeuTu/pull/199

**Comment by hubbardp** [comment]
Now in the "develop" branch.
