### ISSUE TITLE
feature request: Add support for RGB stacks

### ISSUE THREAD

**Issue by AndrewMicallef** [janelia-flyem/NeuTu#153]
I tried to open up some RGB stacks in neutube v1.0z - General on windows and found that the program crashes.

Using a 16-bit rgb tiff the program crashes
The program opens 8-bit rgb tiff, but seams to only preserve 1 channel. 

It's be really cool if you could add support for coloured images in the future.

**Comment by tingzhao** [comment]
It will be easier for me to debug if you can send me sample stacks.

**Comment by AndrewMicallef** [comment]
Consider this a false alarm. 

I think the problem was in the tiff writer I used to save the files. I tried to generate a smaller stack to email to you, (my original was 200+mb) and tested as I went. Saving a stack as an RGB-color tiff in imageJ allowed me to open a 3 channel stack in neutube.

**Comment by AndrewMicallef** [comment]
Also I realise that this repo doesn't seem to be neutube... but this is where the neutube website links to. What happened to the neutube repository?

**Comment by tingzhao** [comment]
We just updated it recently to reorganize different editions. The neutube code is in the neutube branch now, but scheduled to become a separate repository.

**Comment by tingzhao** [comment]
The source code of neuTube has been moved to https://github.com/tingzhao/neutube.
