### ISSUE TITLE
Support multi-res for faster focused proofreading in neu3

### ISSUE THREAD

**Issue by stephenplaza** [janelia-flyem/NeuTu#154]
(preliminary request)

To speed-up focused proofreading, neu3 could fetch a low-rez mesh for the relevant bodies (if available) before fetching higher resolution version showing all supervoxels.

**Comment by hubbardp** [comment]
The "neu3-body-merge-simplest" branch now loads low resolution meshes initially, and has a "Show High Resolution" checkbox that allows the user to switch to a high resolution meshes.

https://github.com/janelia-flyem/NeuTu/commit/a5f6314bd920d7a41e240bf4123c173f33f2e108

**Comment by hubbardp** [comment]
The "neu3-body-merge-simplest" branch has been merged into "develop":
#170
