### ISSUE TITLE
show zoomed out 3D representation of bodies in focused proofreading

### ISSUE THREAD

**Issue by stephenplaza** [janelia-flyem/NeuTu#155]
(preliminary request)

During focused proofreading, it would be nice to display a zoomed-out 3D view of the two bodies being focused proofreading (perhaps in the top right corner of the window) in addition to the more zoomed-in view currently used.  This could provide the user with a multiple perspectives to help guide the decision.

**Comment by hubbardp** [comment]
This "bird's eye view" is in progress.

**Comment by hubbardp** [comment]
Now in the "neu3-body-merge-birds-eye-view" branch:
https://github.com/janelia-flyem/NeuTu/commit/2d0be51d76c06cdabf4476c2e66d30387c604010

**Comment by hubbardp** [comment]
Now released, with the "segmentation_merged" output having the following values for the "build version" key:
Linux:
"neu3-0.1.post1255-0_g37643e3"
Mac:
"neu3-develop-0.1.post1255-0_g37643e3"

**Comment by hubbardp** [comment]
Now in the "develop" branch:
https://github.com/janelia-flyem/NeuTu/pull/176
