### ISSUE TITLE
Problems showing high-res meshes in the focused merge tool since hybrid mesh refactoring

### ISSUE THREAD

**Issue by hubbardp** [janelia-flyem/NeuTu#185]
The following code (merged into the "develop" branch) did considerable refactoring of how Neu3 handles "bodies" that are collections of supervoxel meshes loaded from a tar archive with a specially encoded ID:

https://github.com/janelia-flyem/NeuTu/pull/177/

Since that change, the "Show High Resolution" button in the focused merging tool (taskbodymerge.{h,cpp}) is not working correctly.  It should replace the two bodies' "sparsevol" meshes with the corresponding super voxel meshes, retrieved from a tar archive (when that tar archive exists).  

It seems that the replacement works correctly for one of the bodies.  But for the other, the super voxels seems to appear and then immediately get deleted.  That usually causes a crash in TaskBodyMerge::zoomToMeshes().

**Comment by hubbardp** [comment]
As a test case, use a branch of this node:
http://emdata1.int.janelia.org:8400/#/repo/ecbedddd08034db8b0b0f1529b578d96

Load the following merge protocol JSON:
{
  "file type": "Neu3 task list",
  "file version": 1,
  "task list": [

    {
      "task type": "body merge",
      "supervoxel ID 1": 1249473814, "supervoxel point 1": [ 23784, 10276, 17576 ],
      "supervoxel ID 2": 1249473907, "supervoxel point 2": [ 23774, 10298, 17590 ]
    }
  ]
}

When the low-res (sparesevol) meshes appear, check the "Show High Resolution" box.

**Comment by tingzhao** [comment]
I'm able to fix the problem by handling the body IDs more carefully and skipping hybrid update when a body is presented as supervoxels. But the root problem is a little more complicated than the current solution. More refactoring might be necessary to avoid similar issues in the future.
