### ISSUE TITLE
Feature request: allow placing "Done" ToDos via Assigned Bookmarks table

### ISSUE THREAD

**Issue by schlegelp** [janelia-flyem/NeuTu#320]
I wrote a script to help systematically going over potential open [tips](https://github.com/flyconnectome/dvid_tools/blob/d12be2df1a7c5039808805a0d132108be5c4e6eb/dvidtools/tip.py#L16.). The main difference between this and @stephenplaza's tip detector is the workflow:

It piggy-backs on the "Assigned Bookmarks" table's feature to place invisible bookmarks (right-click --> "Set Checked") to keep track of tips that have already been manually checked. From the user's point of view this is more convenient for two reasons:
1) A simple right click on the entry in the table to mark a tip as checked instead of manually placing `Done` tags in the vicinity
2) The checked entries are highlighted in green

To be consist with previous methods @stephenplaza suggested it would be better if - for this purpose - the assigned bookmarks table would have the option to use `Done` tags instead of bookmarks as this would be in line with previous workflows.

Happy to discuss details here or on Slack.

**Comment by tingzhao** [comment]
This issue has been addressed as a todo table improvement.
