### ISSUE TITLE
Random body becomes selected after closing orthogonal view in Neutu

### ISSUE THREAD

**Issue by knechtc** [janelia-flyem/NeuTu#328]
In Neutu, after activating the orthogonal view and toggling the segmentation using "F" and toggling to view selected bodies using "H" (transparent mode) a random body will become selected once the orthogonal view window is closed.

**Comment by knechtc** [comment]
This also sometimes occurs when you click on an area with no segmentation in orthogonal view.

**Comment by tingzhao** [comment]
Is the first issue of random body selection after closing orthogonal view still there?

**Comment by knechtc** [comment]
The last reported instance of a body being selected after closing orthogonal view was on 5/20/2019
