### ISSUE TITLE
Changing the type of an annotation appends to rather than replaces its tags.

### ISSUE THREAD

**Issue by pgunn** [janelia-flyem/NeuTu#329]
If you create a new annotation (e.g. "to merge"), in DVID it gets the representation under Tags of
```
"Tags": [ "action:merge" ],
"Prop": {
    "action": "to merge",
    ....
},
...
```

If you then double click on it and change the annotation type (e.g. "to split"), the Prop field is updated in DVID to the new value, but the Tag for the annotation is appended to rather than replaced. Meaning you'll get

```
"Tags": [
    "action:merge",
    "action:split",
    ....
],
...
```

**Comment by tingzhao** [comment]
Just applied a fix in neutu-develop post2065. Please check if the problem has been fixed.

**Comment by pgunn** [comment]
Problem is indeed fixed in post2065. Thanks!
