### ISSUE TITLE
Internal representation of new synapses differs from after edits

### ISSUE THREAD

**Issue by pgunn** [janelia-flyem/NeuTu#333]
Right now if I mark a new PSD in NeuTu, it might have a representation like this in DVID:

```{'Pos': [2680, 7835, 3415], 'Kind': 'PostSyn', 'Tags': [], 'Prop': {'user': 'pgunn'}, 'Rels': [{'Rel': 'PostSynTo', 'To': [2654, 7813, 3415]}]}```

bringing up the edit dialogue for that PSD and adding an annotation changes the Tags representation to a None and adds several fields to the Prop unrelated to the annotation:

```{'Pos': [2680, 7835, 3415], 'Kind': 'PostSyn', 'Tags': None, 'Prop': {'annotation': 'yar', 'conf': '1', 'user': 'pgunn'}, 'Rels': [{'Rel': 'PostSynTo', 'To': [2654, 7813, 3415]}]}```

I believe this is also true for T-bars and possibly TODOs - it'd be cool if these representations were made more uniform.

(this is very low priority)

**Comment by tingzhao** [comment]
It's caused by inconsistency in DVID. The problem should be gone since version 0.1.post2299.
