### ISSUE TITLE
Todo List in Neutu does not correctly set todos to "Checked"

### ISSUE THREAD

**Issue by knechtc** [janelia-flyem/NeuTu#340]
Selecting todos in the "Todo List" and pressing the "check selected" button will check the todos. However when you update the list some or all of the todos will revert to unchecked status. After this the checked/unchecked status of the todos often does not match what is displayed in the 3D body view even after using refresh segmentation/refresh data/update bodies.

**Comment by tingzhao** [comment]
Does this happen often? I wasn't able to reproduce the problem.

**Comment by knechtc** [comment]
Very often. I can make it happen on request. patersont has the problem everytime he uses the todo list.
