### ISSUE TITLE
Neutu Feature Request: Quarantine Body Status

### ISSUE THREAD

**Issue by knechtc** [janelia-flyem/NeuTu#365]
A body status of "Quarantine" with lock characteristics similar to the "Unimportant" status and if possible displayed with a red color. This would be used to isolate bodies that require major editing.

**Comment by tingzhao** [comment]
What's the priority of the "Quarantine" status?

**Comment by knechtc** [comment]
I was thinking something similar to "Unimportant" in that merges could be blocked from it but that it could be changed to a different status fairly easily when necessary.

**Comment by stephenplaza** [comment]
I would also consider making the opacity for segmentation layer for this neuron to be slightly greater so it stands out more.
________________________________
