### ISSUE TITLE
Disable default cleave server

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/NeuTu#368]
I learned today that if the `NEU3_CLEAVE_SERVER` variable is not set, then `neu3` uses a default value.  We probably thought that was a good idea when we first implemented cleaving, but in today's multi-volume, multi-team remote work environment, that default behavior just delays the proofreader from understanding that something is wrong.

Can we please just disable the default and emit an error as soon as possible if the user tries to cleave without a valid `NEU3_CLEAVE_SERVER` value?

cc @knechtc

**Comment by tingzhao** [comment]
The default server has been disabled and a warning message will be displayed for a cleaving task if the server is not supplied.

**Comment by stuarteberg** [comment]
Thanks!
