### ISSUE TITLE
Add UI setting for cleave server location

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/NeuTu#370]
Most settings in NeuTu and neu3 are configured in the user interface, but for some reason we decided to make the cleave server address configurable only via the command-line, as an environment variable (`NEU3_CLEAVE_SERVER`).

I don't remember exactly why we did it that way. Perhaps we thought we would usually rely on the default setting ([recently removed][1]), so that environment variable was intended for "power users" who needed a special server.

Anyway, we now ask users to configure that setting every time they launch neu3, so it would be better to make it an "official" part of the UI.  Currently, users (including me) frequently forget or mis-configure this environment variable.

[1]: #368

cc @knechtc @hubbardp

**Comment by stuarteberg** [comment]
Minor note:  Although the environment variable is configured like this:

```
export NEU3_CLEAVE_SERVER=http://emdata4.int.janelia.org:5570/compute-cleave
```

I think the UI should just ask for the server and port (you can hard-code the `/compute-cleave` part).

**Comment by tingzhao** [comment]
The cleaving sever is now configurable in the setting dialog, and `/compute-cleave` is no longer necessary.
