### ISSUE TITLE
How to use skeletonize?

### ISSUE THREAD

**Issue by william-silversmith** [janelia-flyem/NeuTu#371]
Hi Ting!

I was interested in trying out the TEASAR implementation in NeuTu / Neu3, but I've been having trouble finding documentation for how to do it (I tried to ctrl-F "skeleton" in the manuals). I looked through the code and found some references to DVID, but I didn't find the code in the DVID repo. I think I found a `--skeletonize` option, but it's not clear how to use it.

Thanks for any help. ^_^

Will

**Comment by tingzhao** [comment]
Hi Will,

You can run neutu as a command line to perform skeletonization.

- To skeletonize a binary TIF file:

`neutu --command --skeletonize -o <output.swc> <input.tif>`

- To skeletonize a body in DVID:

`neutu --command --skeletonize --bodyid <body id>  '<dvid_server_address>?uuid=<uuid>&segmentation=<segmentation_name>'`

The result will be saved under the keyvalue data <segmentation_name>_skeletons in DVID.

**Comment by william-silversmith** [comment]
Thank you Ting! I'll give this a try.

**Comment by william-silversmith** [comment]
Thank you Ting! I was able to run it.
