### ISSUE TITLE
timestamps everywhere

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/NeuTu#374]
We should start including timestamp for todo annotations and bookmarks.  Same for body annotations.  Am I forgetting any other types of user data?

Ideally, nearly every piece of data that a user creates should be associated with a user ID and a timestamp.  (In some cases, this is already well handled by the kafka log and/or mutations log, such as merge commands.)

**Comment by tingzhao** [comment]
@stuarteberg Should the timestamp be updated whenever an annotation is changed? For example, when an annotation is changed by merging another annotation during body merging, should the timestamp of this annotation be updated too?

**Comment by tingzhao** [comment]
The new annotations will have the following fields:
`createdTime`: time when created
`modifiedTime`: time when an existing annotation is modified
`checkedTime`: time when annotation is checked or a checked annotation is created
