### ISSUE TITLE
to-do statuses

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/NeuTu#391]
We need a way to mark "todo" annotations as "Looked at; won't fix"

**Comment by olbris** [comment]
I'm imagining you'd like to add another checkbox to the to do dialog box, similar to the existing "Checked" one, with a label maybe like "Checked-won't fix". We could then add another property to the to do annotation with the results. Or we could do something more sketchy...current "checked" property is _not_ boolean but is a string "0" or "1". We could assign "-1" as "checked - won't fix". But who knows what tools would choke on that.

Either way, I think I've located the code to change this. If you have something else in mind, more detail needed.

**Comment by stuarteberg** [comment]
I don’t have a super strong opinion, but I like the second option. However, instead of “-1”, using an actual word(s).

**Comment by olbris** [comment]
I am proceeding with the assumption that "checked-won't fix" should be the same visually as "checked" (eg, in 2d plane; it'll have its own checkbox in the to do dialog box). Currently the graphics code looks at `ZFlyEmToDoItem::isChecked()`, and I'd rather leave that as-is. I think this is consistent with intended use.

**Comment by olbris** [comment]
Basically done as "checked--wontfix". Came across some related to do issues in production that I didn't get enough time to fix, but nothing is more broken than production.
