### ISSUE TITLE
report last user to modify body in log box

### ISSUE THREAD

**Issue by olbris** [janelia-flyem/NeuTu#392]
Discussed in 2022-09-28 software meeting. Bill will provide API in `labelmap` data type, probably query string off `index` endpoint.

**Comment by olbris** [comment]
@stuarteberg What info do you want reported? New endpoint returns: 

`{"num_voxels":6745734794,"last_mutid":1000626385,"last_mod_time":"2022-08-04T14:00:31-04:00","last_mod_user":"phillipse","last_mod_app":"NeuTu"}`

All three of user, time, app of last modification? I'm thinking a message like: 

`Last modfied by phillipse/NeuTu at 2022-08-04T14:00:31-04:00`

BTW, I'm going to put it on-demand in the already-existing right click on body to choose Body>Body profile, which is kind of a body "get info".

**Comment by stuarteberg** [comment]
That looks great to me.
