### ISSUE TITLE
Support for UUID:branch syntax

### ISSUE THREAD

**Issue by olbris** [janelia-flyem/NeuTu#395]
Tested; seems to partly work in NeuTu, but apparently fails in lowtis/libdvidcpp?

**Comment by olbris** [comment]
Further testing indicates it's a `libdvidcpp` problem. Details are hard to extract, though.

**Comment by stuarteberg** [comment]
What is the symptom you're encountering?  An exception?  A segfault?

A brief test using the Python bindings for `libdvidcpp` seems to work:

```python
from libdvid import DVIDNodeService
ns = DVIDNodeService('http://emdata6.int.janelia.org:8000', 'f3969:master')
info = ns.get_typeinfo('segmentation')
```

```python
# Again, this time just ':master'
ns = DVIDNodeService('http://emdata6.int.janelia.org:8000', ':master')
info = ns.get_typeinfo('segmentation')
```

**Comment by olbris** [comment]
I'm trying to isolate it. The error line happens when retrieving grayscale:
`ERROR 2022-09-21T15:32:33.778 ../gui/dvid/zdvidreader.cpp @ 4267 [ ZStack *ZDvidReader::readGrayScaleLowtis(int, int, int, int, int, int, int, int, bool) const ] DVID Error (200): DVIDConnection error (CURLE_URL_MALFORMAT): http://emdata6.int.janelia.org:9000/api/node/f3969:master/grayscale/specificblocks?blocks=0,0,473,` (with many more block triplets). Haven't reproduced with the Python bindings yet, but I am working on it. The error originates in `DVIDConnection::make_request()` line 369.

**Comment by olbris** [comment]
Traced it back into NeuTu. There's some serious black magic in there determining what levels of grayscale are present, and NeuTu messes it up when trying to locate grayscale instances in parent nodes (which it can't find due to the UUID:branch syntax). It wrongly believes it only has zoom level 0 available and requests all the grayscale for one slice of the whole brain. The URL listing all the blocks is 20M long and fails.

Investigating how to fix...

**Comment by stuarteberg** [comment]
I was disappointed to see that the libdvid python bindings do not bind the `/specificblocks` endpoint, so I added support.  However, it's not returning what I expect.

For some reason the following call to DVID returns an empty file:

```
http://emdata6.int.janelia.org:9000/api/node/f3969/segmentation/specificblocks?blocks=493,426,770&compression=blocks&scale=0
```

And if I switch that to `grayscale` I get an error from dvid about the "minishard" from which the data is supposed to be fetched out of the neuroglancer precomputed volume.

```
http://emdata6.int.janelia.org:9000/api/node/f3969/grayscale/specificblocks?blocks=493,426,770
```

Error 400:
```
No minishard map found in shard "8x8x8/04ecb.shard" for minishard 3
 (/api/node/f3969/grayscale/specificblocks).
```


It smells like I'm doing something dumb, such as swapping X and Z.  But as far as I can tell that's not the problem.

**Comment by olbris** [comment]
I saw that error when testing with some URLs in the browser. As far as I can tell, it's orthogonal to the node:branch syntax issue.

**Comment by stuarteberg** [comment]
@DocSavage Do you know why the two REST calls above don't return anything?

**Comment by olbris** [comment]
When a DVID server has only one repo, we'd even like to be able to drop the UUID part, just leaving eg `:master` (only `:branch`). Accommodate that in the current fix, if possible (it is relevant).
