### ISSUE TITLE
enable users to add overlay a grid in neutu on the 2D image

### ISSUE THREAD

**Issue by stephenplaza** [janelia-flyem/NeuTu#44]
When doing manual synapse annotation, it is useful to have a grid of lines overlayed on the image, as a guide.

The user should be able to specify a bounding box in neutu which will cause a grid to appear.  This view should be easy to toggle on and off with a button.

**Comment by tingzhao** [comment]
I'm wondering how a grid can be helpful. Did any specific user request this feature?

**Comment by stephenplaza** [comment]
Pat requested the feature.

When you are annotating synapses, it can be easy to lose track of where you are in space.  The grid gives you some way to look through the data in a more structured manner.  There may be another way to do this but this is what was done in Raveler.
