### ISSUE TITLE
Color map (named vs unnamed)

### ISSUE THREAD

**Issue by takemuras** [janelia-flyem/NeuTu#6]
Color maps will be useful for efficient proofreading and neuron refinement.  An initial requirement for the color map is to label all the neurons that has not been corrected in red.  Then a body turns green when it's body status is changed to 'corrected' after manual proofreading.

**Comment by stephenplaza** [comment]
This might actually be a very complicated request since the notion of body status needs to be changed significantly, in my opinion.  There are multiple stages of correctness for instance depending on what you want to accomplish.

**Comment by takemuras** [comment]
How about named vs unnamed?  Visualizing body status in color in the stack would be a key feature for me to proceed body refinement.  Color maps have been used in Raveler also to visualize specific neurons or cell types such as to see Mi1 and T4 cells in different colors.  This is super useful for analysis purpose.

**Comment by stephenplaza** [comment]
I agree it is useful.  In fact, I think it is absolutely critical that we come up with a good system here.  I think Raveler was actually not nearly good enough.  But I like your name/un-named distinction for now.  That seems simple and won't conflict with a more sophisticated tracking system in the future.

**Comment by tingzhao** [comment]
The color map can be created in the sequencer now.
